add error page
drimov/ProjetReact pull request #32
Opened 2023-09-06 15:46 UTC by ValM34

2023-09-06 16:58 UTC, drimov requested changes

2023-09-06 16:58 UTC, drimov commented on src/pages/Error404.tsx
Il te manque un bouton pour revenir et c'est ok

2023-09-06 19:29 UTC, ValM34 commented on src/pages/Error404.tsx
Effectivement j'avais oublié ! C'est ajouté.

2023-09-10 14:29 UTC, ValM34 commented
Pull request fermée après la création d'une nouvelle branche. Lien de la nouvelle PR : https://github.com/drimov/ProjetReact/compare/creation-d-une-page-d-erreur-new?expand=1

2023-09-10 14:29 UTC, closed without merging