Création de page de recherche V2
drimov/ProjetReact pull request #81
Opened 2023-09-12 20:00 UTC by BambaThiam

2023-09-13 07:20 UTC, drimov commented
J'ai rajouté des directives en commentaire dans l'issue correspondant.

2023-09-13 07:21 UTC, drimov requested changes
J'ai rajouté des directives en commentaire dans l'issue correspondant.

2023-09-13 23:02 UTC, BambaThiam commented
Setup intégré

2023-09-14 06:16 UTC, drimov commented
gros soucis coté responsive mobile: 
![image](https://github.com/drimov/ProjetReact/assets/7766411/2e9d7f9f-b69e-4fb7-ae1c-d5d3bedc1e97)
![image](https://github.com/drimov/ProjetReact/assets/7766411/2077b85a-8a50-42a1-b434-267dbd8b0d39)

le choix de la couleur est discutable : on doit garder un thème cohérent.
Dans l'ensemble c'est vraiment bien fait, bien joué 👍

2023-09-14 06:20 UTC, drimov requested changes
gros soucis coté responsive mobile: 
![image](https://github.com/drimov/ProjetReact/assets/7766411/2e9d7f9f-b69e-4fb7-ae1c-d5d3bedc1e97)


![image](https://github.com/drimov/ProjetReact/assets/7766411/7dd40e1b-d628-492e-b7b5-d8f1608f69c3)
Attention ici, par défaut tu est déjà dans public, il te propose la correction.

![image](https://github.com/drimov/ProjetReact/assets/7766411/3e2de8ee-12bd-43c0-abb7-381f2c512c96)
Rajoute un state pour pouvoir avoir savoir quel onglet est actif

Pour les infos base toi sur l'API pour voir s'il existe bien une propriété qui donne le temps de la recette par exemple
le choix de la couleur est discutable : on doit garder un thème cohérent.
Dans l'ensemble c'est vraiment bien fait, bien joué 👍

2023-09-22 18:03 UTC, merged